### ISSUE TITLE
Is anyone anymore maintaining actively this repository?

### ISSUE THREAD

**Issue by Frans-L** [singer-io/tap-chargebee#99]
Hi all,

I'm wondering whether this repository is anymore actively maintained. If this isn’t maintained actively by anyone, are there any plans to share the maintenance rights with someone else, so the community could keep improving this library? 😄 

There seem to be some open issues and PRs that no one seems to have reacted to for over 1 year, which hints that there might not be anyone here to maintain.

About the open issues, for instance, `tax_rate` is stored as an integer even though it's double. It makes this plugin unusable when needing access to the US city taxes and US special taxes which can be under 1%.

See the Chargebee docs:
https://apidocs.chargebee.com/docs/api/invoices?prod_cat_ver=2#invoice_line_item_taxes_tax_rate
![image](https://github.com/singer-io/tap-chargebee/assets/29607206/b4d9753f-e7ba-4645-b387-134b56b2398a)

The issue has been reported (https://github.com/singer-io/tap-chargebee/issues/81) and a fix has been made (https://github.com/singer-io/tap-chargebee/pull/80) however it hasn't been merged or reviewed over 1.5 years.

Thanks in advance!  🙏

**Comment by RushiT0122** [comment]
@Frans-L we will look into this issue.

**Comment by Frans-L** [comment]
Amazing! Thank you :)
